apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whisper.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
{{- with .Values.env }}
  whisper_model: "{{ .whisperModel | default "base" }}"
  uvicorn_host: "{{ .uvicornHost | default "0.0.0.0" }}"
  uvicorn_port: "{{ .uvicornPort | default "8000" }}"
  logging_level: "{{ .loggingLevel | default "INFO" }}"
{{- end }}